.PHONY: clean
clean:
#	find . -type d -maxdepth 1 |grep "./" | xargs -I {} make clean -C {} 

.PHONY: build
build:
#	find . -type d -maxdepth 1 |grep "./" | xargs -I {} make build -C {} 

.PHONY: sim
sim:
#	find . -type d -maxdepth 1 |grep "./" | xargs -I {} make sim -C {} 

.PHONY: vcs_sim
vcs_sim:
#	find . -type d -maxdepth 1 |grep "./" | xargs -I {} make vcs_sim -C {} 

.PHONY: test
test:
#	find . -type d -maxdepth 1 |grep "./" | xargs -I {} make test -C {} 

.PHONY: vcs_test
vcs_test:
#	find . -type d -maxdepth 1 |grep "./" | xargs -I {} make vcs_test -C {} 
