TOPMODULE=mm
RTL=mm.v
THREAD=cthread_mm.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=320mm512.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../../
CONFIG=$(ROOTDIR)/sample/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/sample/base.mk
