TOPMODULE=mm
RTL=mm.v
THREAD=cthread_mm.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
ROOTDIR=../../../../
MEM=320mm512.hex
MEMIMG=--memimg=$(MEM)
CONFIG=$(ROOTDIR)/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/base.mk
