TOPMODULE=random_write
RTL=random_write.v
THREAD=cthread_random_write.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
ROOTDIR=../../../
MEM=$(ROOTDIR)/mem-incr.hex
MEMIMG=--memimg=$(MEM)
CONFIG=$(ROOTDIR)/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/base.mk
