.PHONY: clean
clean:
	make clean -C test

.PHONY: build
build:
	make build -C test

.PHONY: sim
sim:
	make sim -C test

.PHONY: vcs_sim
vcs_sim:
	make vcs_sim -C test

.PHONY: test
test:
	make test -C test

.PHONY: vcs_test
vcs_test:
	make vcs_test -C test
