.PHONY: clean
clean:
	make clean -C iochannel
	make clean -C multipage_memory
	make clean -C multithread
	make clean -C nonblocking
	make clean -C scattergather
	make clean -C single_memory
	make clean -C stream
	make clean -C vectorsum
