TOPMODULE=st
RTL=st.v
THREAD=cthread_st.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=330stencil512.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../../
CONFIG=$(ROOTDIR)/sample/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/sample/base.mk
