TOPMODULE=sequential_read
RTL=sequential_read.v
THREAD=cthread_sequential_read.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=../../mem-incr.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../
CONFIG=$(ROOTDIR)/sample/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/sample/base.mk
