TOPMODULE=sequential_read
RTL=sequential_read.v
THREAD=cthread_sequential_read.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
ROOTDIR=../../../
MEM=$(ROOTDIR)/mem-incr.hex
MEMIMG=--memimg=$(MEM)
CONFIG=$(ROOTDIR)/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/base.mk
