PYTHON=python3
#OPT=-m pdb
TARGET=controlthread.py
INPUT=../../sample/test/single_memory/ctrl_thread.py

.PHONY: compile
compile:
	$(PYTHON) $(OPT) $(TARGET) $(INPUT)

.PHONY: clean
clean:
	rm -rf *.pyc __pycache__ parsetab.py *.out *.v
