TOPMODULE=random_read
RTL=random_read.v
THREAD=cthread_random_read.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=../../mem-incr.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../
CONFIG=$(ROOTDIR)/sample/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/sample/base.mk
