TOPMODULE=Cache
RTL=cache.v
THREAD=cache_thread.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=mem.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../
CONFIG=$(ROOTDIR)/sample/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/sample/base.mk
