TOPMODULE=Cache
RTL=cache.v
THREAD=cache_thread.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
ROOTDIR=../../../
MEM=mem.hex
MEMIMG=--memimg=$(MEM)
CONFIG=$(ROOTDIR)/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/base.mk
