TOPMODULE=userlogic
RTL=timer.v
THREAD=cthread_timer.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=../../mem-incr.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../
CONFIG=$(ROOTDIR)/sample/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/sample/base.mk
