.PHONY: clean
clean:
	make clean -C app
	make clean -C benchmark
#	make clean -C contest
	make clean -C microbench
	make clean -C miniapp
#	make clean -C myhdl
#	make clean -C original_coram
	make clean -C test

.PHONY: build
build:
	make build -C app
	make build -C benchmark
#	make build -C contest
	make build -C microbench
	make build -C miniapp
#	make build -C myhdl
#	make build -C original_coram
	make build -C test

.PHONY: sim
sim:
	make sim -C app
	make sim -C benchmark
#	make sim -C contest
	make sim -C microbench
	make sim -C miniapp
#	make sim -C myhdl
#	make sim -C original_coram
	make sim -C test

.PHONY: vcs_sim
vcs_sim:
	make vcs_sim -C app
	make vcs_sim -C benchmark
#	make vcs_sim -C contest
	make vcs_sim -C microbench
	make vcs_sim -C miniapp
#	make vcs_sim -C myhdl
#	make vcs_sim -C original_coram
	make vcs_sim -C test

.PHONY: test
test:
	make test -C app
	make test -C benchmark
#	make test -C contest
	make test -C microbench
	make test -C miniapp
#	make test -C myhdl
#	make test -C original_coram
	make test -C test

.PHONY: vcs_test
vcs_test:
	make vcs_test -C app
	make vcs_test -C benchmark
#	make vcs_test -C contest
	make vcs_test -C microbench
	make vcs_test -C miniapp
#	make vcs_test -C myhdl
#	make vcs_test -C original_coram
	make vcs_test -C test
