.PHONY: clean
clean:
	make clean -C nologic
	make clean -C single_memory

.PHONY: build
build:
	make build -C nologic
	make build -C single_memory

.PHONY: sim
sim:
	make sim -C nologic
	make sim -C single_memory

.PHONY: vcs_sim
vcs_sim:
	make vcs_sim -C nologic
	make vcs_sim -C single_memory

.PHONY: test
test:
	make test -C nologic
	make test -C single_memory

.PHONY: vcs_test
vcs_test:
	make vcs_test -C nologic
	make vcs_test -C single_memory
