.PHONY: clean
clean:
	make clean -C ./utils
	make clean -C ./vparser
	make clean -C ./definition_analyzer
	make clean -C ./optimizer
	make clean -C ./ast_to_code
	rm -rf *.pyc __pycache__ *.out parsetab.py *.html
