TOPMODULE=pointer_read_memory
RTL=pointer_read_memory.v
THREAD=cthread_pointer_read_memory.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
MEM=../../mem-incr.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../
CONFIG=$(ROOTDIR)/sample/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/sample/base.mk
