TOPMODULE=userlogic
RTL=userlogic.v
THREAD=ctrl_thread_0.py ctrl_thread_1.py
#TEST=testbench.v
#USERTEST=--usertest=$(TEST)
MEM=../../mem-incr.hex
MEMIMG=--memimg=$(MEM)
ROOTDIR=../../../
CONFIG=$(ROOTDIR)/sample/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/sample/base.mk
