TOPMODULE=userlogic
RTL=userlogic.v
THREAD=ctrl_thread_0.py ctrl_thread_1.py
#TEST=testbench.v
#USERTEST=--usertest=$(TEST)
ROOTDIR=../../
MEM=$(ROOTDIR)/mem-incr.hex
MEMIMG=--memimg=$(MEM)
CONFIG=$(ROOTDIR)/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/base.mk
