.PHONY: clean
clean:
	make clean -C doublebuffer
	make clean -C iochannel
	make clean -C ioregister
	make clean -C multipage
	make clean -C multithread
	make clean -C nonblocking
	make clean -C scattergather
	make clean -C single_memory
	make clean -C stream

.PHONY: build
build:
	make build -C doublebuffer
	make build -C iochannel
	make build -C ioregister
	make build -C multipage
	make build -C multithread
	make build -C nonblocking
	make build -C scattergather
	make build -C single_memory
	make build -C stream

.PHONY: sim
sim:
	make sim -C doublebuffer
	make sim -C iochannel
	make sim -C ioregister
	make sim -C multipage
	make sim -C multithread
	make sim -C nonblocking
	make sim -C scattergather
	make sim -C single_memory
	make sim -C stream

.PHONY: vcs_sim
vcs_sim:
	make vcs_sim -C doublebuffer
	make vcs_sim -C iochannel
	make vcs_sim -C ioregister
	make vcs_sim -C multipage
	make vcs_sim -C multithread
	make vcs_sim -C nonblocking
	make vcs_sim -C scattergather
	make vcs_sim -C single_memory
	make vcs_sim -C stream

.PHONY: test
test:
	make test -C doublebuffer
	make test -C iochannel
	make test -C ioregister
	make test -C multipage
	make test -C multithread
	make test -C nonblocking
	make test -C scattergather
	make test -C single_memory
	make test -C stream

.PHONY: vcs_test
vcs_test:
	make vcs_test -C doublebuffer
	make vcs_test -C iochannel
	make vcs_test -C ioregister
	make vcs_test -C multipage
	make vcs_test -C multithread
	make vcs_test -C nonblocking
	make vcs_test -C scattergather
	make vcs_test -C single_memory
	make vcs_test -C stream
