TOPMODULE=userlogic
RTL=timer.v
THREAD=cthread_timer.py
TEST=testbench.v
USERTEST=--usertest=$(TEST)
ROOTDIR=../../../
MEM=$(ROOTDIR)/mem-incr.hex
MEMIMG=--memimg=$(MEM)
CONFIG=$(ROOTDIR)/default.config
INCLUDE=-I $(ROOTDIR)/include/
include $(ROOTDIR)/base.mk
